import 'trainer.dart';
import 'pokemon_list.dart';

final List<Trainer> trainerList = [
  Trainer(
    trainerName: 'Ash Ketchum',
    trainerId: 1,
    wins: 25,
    losses: 10,
    completedTasks: 5,
    pokemonCount: 6,
    pokemonSlot1: 10,
    pokemonSlot2: 1,
    pokemonSlot3: 20,
    pokemonSlot4: 33,
    pokemonSlot5: 14,
    pokemonSlot6: 30,
  ),
  Trainer(
    trainerName: 'Misty',
    trainerId: 2,
    wins: 18,
    losses: 12,
    completedTasks: 7,
    pokemonCount: 6,
    pokemonSlot1: 6,
    pokemonSlot2: 7,
    pokemonSlot3: 8,
    pokemonSlot4: 9,
    pokemonSlot5: 10,
    pokemonSlot6: 11,
  ),
  Trainer(
    trainerName: 'Brock',
    trainerId: 3,
    wins: 22,
    losses: 8,
    completedTasks: 10,
    pokemonCount: 6,
    pokemonSlot1: 12,
    pokemonSlot2: 13,
    pokemonSlot3: 14,
    pokemonSlot4: 15,
    pokemonSlot5: 16,
    pokemonSlot6: 17,
  ),
  Trainer(
    trainerName: 'Gary Oak',
    trainerId: 4,
    wins: 30,
    losses: 5,
    completedTasks: 12,
    pokemonCount: 6,
    pokemonSlot1: 18,
    pokemonSlot2: 19,
    pokemonSlot3: 20,
    pokemonSlot4: 21,
    pokemonSlot5: 22,
    pokemonSlot6: 23,
  ),
  Trainer(
    trainerName: 'Erika',
    trainerId: 5,
    wins: 15,
    losses: 15,
    completedTasks: 8,
    pokemonCount: 6,
    pokemonSlot1: 24,
    pokemonSlot2: 25,
    pokemonSlot3: 26,
    pokemonSlot4: 27,
    pokemonSlot5: 28,
    pokemonSlot6: 29,
  ),
  Trainer(
    trainerName: 'Lt. Surge',
    trainerId: 6,
    wins: 20,
    losses: 13,
    completedTasks: 6,
    pokemonCount: 6,
    pokemonSlot1: 30,
    pokemonSlot2: 31,
    pokemonSlot3: 32,
    pokemonSlot4: 33,
    pokemonSlot5: 34,
    pokemonSlot6: 35,
  ),
  Trainer(
    trainerName: 'Sabrina',
    trainerId: 7,
    wins: 28,
    losses: 7,
    completedTasks: 11,
    pokemonCount: 6,
    pokemonSlot1: 36,
    pokemonSlot2: 0,
    pokemonSlot3: 1,
    pokemonSlot4: 2,
    pokemonSlot5: 3,
    pokemonSlot6: 4,
  ),
  Trainer(
    trainerName: 'Koga',
    trainerId: 8,
    wins: 17,
    losses: 14,
    completedTasks: 9,
    pokemonCount: 6,
    pokemonSlot1: 5,
    pokemonSlot2: 6,
    pokemonSlot3: 7,
    pokemonSlot4: 8,
    pokemonSlot5: 9,
    pokemonSlot6: 10,
  ),
  Trainer(
    trainerName: 'Blaine',
    trainerId: 9,
    wins: 23,
    losses: 9,
    completedTasks: 13,
    pokemonCount: 6,
    pokemonSlot1: 11,
    pokemonSlot2: 12,
    pokemonSlot3: 13,
    pokemonSlot4: 14,
    pokemonSlot5: 15,
    pokemonSlot6: 16,
  ),
  Trainer(
    trainerName: 'Giovanni',
    trainerId: 10,
    wins: 35,
    losses: 3,
    completedTasks: 15,
    pokemonCount: 6,
    pokemonSlot1: 17,
    pokemonSlot2: 18,
    pokemonSlot3: 19,
    pokemonSlot4: 20,
    pokemonSlot5: 21,
    pokemonSlot6: 22,
  ),
];
