import 'trainer.dart';
import 'pokemon_list.dart';

final List<Trainer> trainerList = [
  Trainer(
    username: 'Ash Ketchum',
    trainerId: '1',
    wins: 25,
    losses: 10,
    completedTasks: 5,
    level: 10,
    experiencePoints: 1000,
    sex: 'male',
    createdAt: DateTime.now(),
    pokemonSlot1: '10',
    pokemonSlot2: '1',
    pokemonSlot3: '20',
    pokemonSlot4: '33',
    pokemonSlot5: '14',
    pokemonSlot6: '30',
    favoritePokemon: '10',
  ),
  Trainer(
    username: 'Misty',
    trainerId: '2',
    wins: 18,
    losses: 12,
    completedTasks: 7,
    level: 9,
    experiencePoints: 900,
    sex: 'female',
    createdAt: DateTime.now(),
    pokemonSlot1: '6',
    pokemonSlot2: '7',
    pokemonSlot3: '8',
    pokemonSlot4: '9',
    pokemonSlot5: '10',
    pokemonSlot6: '11',
    favoritePokemon: '6',
  ),
  Trainer(
    username: 'Brock',
    trainerId: '3',
    wins: 22,
    losses: 8,
    completedTasks: 10,
    level: 8,
    experiencePoints: 800,
    sex: 'male',
    createdAt: DateTime.now(),
    pokemonSlot1: '12',
    pokemonSlot2: '13',
    pokemonSlot3: '14',
    pokemonSlot4: '15',
    pokemonSlot5: '16',
    pokemonSlot6: '17',
    favoritePokemon: '12',
  ),
  Trainer(
    username: 'Gary Oak',
    trainerId: '4',
    wins: 30,
    losses: 5,
    completedTasks: 12,
    level: 12,
    experiencePoints: 1200,
    sex: 'male',
    createdAt: DateTime.now(),
    pokemonSlot1: '18',
    pokemonSlot2: '19',
    pokemonSlot3: '20',
    pokemonSlot4: '21',
    pokemonSlot5: '22',
    pokemonSlot6: '23',
    favoritePokemon: '18',
  ),
  Trainer(
    username: 'Erika',
    trainerId: '5',
    wins: 15,
    losses: 15,
    completedTasks: 8,
    level: 7,
    experiencePoints: 700,
    sex: 'female',
    createdAt: DateTime.now(),
    pokemonSlot1: '24',
    pokemonSlot2: '25',
    pokemonSlot3: '26',
    pokemonSlot4: '27',
    pokemonSlot5: '28',
    pokemonSlot6: '29',
    favoritePokemon: '24',
  ),
  Trainer(
    username: 'Lt. Surge',
    trainerId: '6',
    wins: 20,
    losses: 13,
    completedTasks: 6,
    level: 6,
    experiencePoints: 600,
    sex: 'male',
    createdAt: DateTime.now(),
    pokemonSlot1: '30',
    pokemonSlot2: '31',
    pokemonSlot3: '32',
    pokemonSlot4: '33',
    pokemonSlot5: '34',
    pokemonSlot6: '35',
    favoritePokemon: '30',
  ),
  Trainer(
    username: 'Sabrina',
    trainerId: '7',
    wins: 28,
    losses: 7,
    completedTasks: 11,
    level: 11,
    experiencePoints: 1100,
    sex: 'female',
    createdAt: DateTime.now(),
    pokemonSlot1: '36',
    pokemonSlot2: '0',
    pokemonSlot3: '1',
    pokemonSlot4: '2',
    pokemonSlot5: '3',
    pokemonSlot6: '4',
    favoritePokemon: '36',
  ),
  Trainer(
    username: 'Koga',
    trainerId: '8',
    wins: 17,
    losses: 14,
    completedTasks: 9,
    level: 9,
    experiencePoints: 900,
    sex: 'male',
    createdAt: DateTime.now(),
    pokemonSlot1: '5',
    pokemonSlot2: '6',
    pokemonSlot3: '7',
    pokemonSlot4: '8',
    pokemonSlot5: '9',
    pokemonSlot6: '10',
    favoritePokemon: '5',
  ),
  Trainer(
    username: 'Blaine',
    trainerId: '9',
    wins: 23,
    losses: 9,
    completedTasks: 13,
    level: 13,
    experiencePoints: 1300,
    sex: 'male',
    createdAt: DateTime.now(),
    pokemonSlot1: '11',
    pokemonSlot2: '12',
    pokemonSlot3: '13',
    pokemonSlot4: '14',
    pokemonSlot5: '15',
    pokemonSlot6: '16',
    favoritePokemon: '11',
  ),
  Trainer(
    username: 'Giovanni',
    trainerId: '10',
    wins: 35,
    losses: 3,
    completedTasks: 15,
    level: 15,
    experiencePoints: 1500,
    sex: 'male',
    createdAt: DateTime.now(),
    pokemonSlot1: '17',
    pokemonSlot2: '18',
    pokemonSlot3: '19',
    pokemonSlot4: '20',
    pokemonSlot5: '21',
    pokemonSlot6: '22',
    favoritePokemon: '17',
  ),
];
